version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: gita
      POSTGRES_PASSWORD: gita123
      POSTGRES_DB: gita_companion
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage

volumes:
  postgres_data:
  qdrant_data: 